# Generated by Django 5.2.6 on 2025-09-29 09:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('age_category_children', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.BooleanField()),
                ('birthday', models.DateField()),
                ('phone_number', models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(80000000000), django.core.validators.MaxValueValidator(89999999999)])),
                ('qualification', models.CharField(choices=[('Воспитатель детского сада', 'Teacher'), ('Старший воспитатель', 'Senior Teacher'), ('Методист', 'Methodist'), ('Музыкальный руководитель', 'Music Director'), ('Педагог-психолог', 'Psychologist'), ('Логопед', 'Speech Therapist'), ('Дефектолог', 'Defectologist'), ('Физкультурный руководитель', 'Pe Teacher'), ('Помощник воспитателя', 'Teacher Assistant'), ('Заведующий детским садом', 'Kindergarten Head')], max_length=50, unique=True)),
                ('work_experience', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee'), ('Parent', 'Parent')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_event', models.DateTimeField()),
                ('count_participants', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kindergarten_app_.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age_group', models.CharField(choices=[('Младшая', 'Junior'), ('Средняя', 'Middle'), ('Старшая', 'Senior')], max_length=10)),
                ('count_children', models.PositiveIntegerField(default=0)),
                ('educational_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten_app_.educationalprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.BooleanField()),
                ('birthday', models.DateField()),
                ('transfer_date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kindergarten_app_.group')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalContraindicationsChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten_app_.child')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(80000000000), django.core.validators.MaxValueValidator(89999999999)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kindergarten_app_.user')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kindergarten_app_.user'),
        ),
        migrations.CreateModel(
            name='AssignedEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Воспитатель детского сада', 'Teacher'), ('Старший воспитатель', 'Senior Teacher'), ('Методист', 'Methodist'), ('Музыкальный руководитель', 'Music Director'), ('Педагог-психолог', 'Psychologist'), ('Логопед', 'Speech Therapist'), ('Дефектолог', 'Defectologist'), ('Физкультурный руководитель', 'Pe Teacher'), ('Помощник воспитателя', 'Teacher Assistant'), ('Заведующий детским садом', 'Kindergarten Head')], max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten_app_.employee')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten_app_.group')),
            ],
            options={
                'unique_together': {('group', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='ListParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten_app_.additionalevent')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten_app_.child')),
            ],
            options={
                'unique_together': {('additional_event', 'child')},
            },
        ),
        migrations.CreateModel(
            name='ListsEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten_app_.educationalprogram')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten_app_.event')),
            ],
            options={
                'unique_together': {('educational_program', 'event')},
            },
        ),
        migrations.CreateModel(
            name='ParentsChilds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten_app_.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten_app_.parent')),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
