# Generated by Django 5.2.6 on 2025-10-06 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_app_', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listparticipants',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='kindergarten_app_.event'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='listparticipants',
            unique_together={('event', 'child')},
        ),
        migrations.RemoveField(
            model_name='listparticipants',
            name='additional_event',
        )
    ]

